// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpQQAscZmlwaryNeN5CWzjLnHEXnewQg0',
    appId: '1:885864277840:web:c0bd7d7c0c41873f6cae55',
    messagingSenderId: '885864277840',
    projectId: 'service-ec2e6',
    authDomain: 'service-ec2e6.firebaseapp.com',
    databaseURL: 'https://service-ec2e6-default-rtdb.firebaseio.com',
    storageBucket: 'service-ec2e6.firebasestorage.app',
    measurementId: 'G-WSN7S0N4Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMOTa6e7AKjCo9EcdopeoMrq90j832Frs',
    appId: '1:885864277840:android:0fdeab4730d2f5096cae55',
    messagingSenderId: '885864277840',
    projectId: 'service-ec2e6',
    databaseURL: 'https://service-ec2e6-default-rtdb.firebaseio.com',
    storageBucket: 'service-ec2e6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpQQAscZmlwaryNeN5CWzjLnHEXnewQg0',
    appId: '1:885864277840:web:4b03c850392334036cae55',
    messagingSenderId: '885864277840',
    projectId: 'service-ec2e6',
    authDomain: 'service-ec2e6.firebaseapp.com',
    databaseURL: 'https://service-ec2e6-default-rtdb.firebaseio.com',
    storageBucket: 'service-ec2e6.firebasestorage.app',
    measurementId: 'G-WJ97Q8N6YT',
  );
}
